/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {ApiGenericResponseUserResponseDto} from '../../models/api-generic-response-user-response-dto';

export interface GetUserInfoByUuid$Params {
  userUuid: string;
}

export function getUserInfoByUuid(http: HttpClient, rootUrl: string, params: GetUserInfoByUuid$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseUserResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getUserInfoByUuid.PATH, 'get');
  if (params) {
    rb.path('userUuid', params.userUuid, {});
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseUserResponseDto>;
    })
  );
}

getUserInfoByUuid.PATH = '/api/v1/users/{userUuid}';
