spring:
  application:
    name: GastroManager
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: admin
  jackson:
    deserialization:
      fail-on-unknown-properties: true

api:
  endpoint:
    base-url: /api/v1

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        data:
          jpa: TRACE
      orm:
        jdbc:
          bind: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

## Datasource config
#spring.datasource.url=jdbc:postgresql://localhost:5432/
#spring.datasource.username=postgres
#spring.datasource.password=admin




---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://ep-red-credit-a63sdemi.us-west-2.aws.neon.tech/gastromanager-db?sslmode=require
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver