/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ApiGenericResponseString {
  data?: string;
  flag?: boolean;
  message?: string;
  timestamp?: string;
}
