/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {ProductItemResponseDto} from '../models/product-item-response-dto';

export interface ApiGenericResponseProductItemResponseDto {
  data?: ProductItemResponseDto;
  flag?: boolean;
  message?: string;
  timestamp?: string;
}
