/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {IngredientResponseDto} from '../models/ingredient-response-dto';

export interface ApiGenericResponseIngredientResponseDto {
  data?: IngredientResponseDto;
  flag?: boolean;
  message?: string;
  timestamp?: string;
}
