/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {OrderResponseDto} from '../models/order-response-dto';

export interface ApiGenericResponseListOrderResponseDto {
  data?: Array<OrderResponseDto>;
  flag?: boolean;
  message?: string;
  timestamp?: string;
}
