/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IngredientRequestDto {
  availableStock?: number;
  minimumStockQuantity?: number;
  name?: string;
  pricePerUnit?: number;
  supplier?: string;
  unit?: string;
}
