/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IngredientResponseDto {
  availableStock?: number;
  createdBy?: string;
  createdDate?: string;
  minimumStockQuantity?: number;
  name?: string;
  pricePerUnit?: number;
  supplier?: string;
  unit?: string;
  updatedBy?: string;
  updatedDate?: string;
  uuid?: string;
}
