/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {OrderItemResponse} from '../models/order-item-response';

export interface OrderResponseDto {
  orderItems?: Array<OrderItemResponse>;
  status?: 'PENDING' | 'PREPARING' | 'READY' | 'ON_TABLE' | 'COMPLETED' | 'CANCELLED';
  totalPrice?: number;
  userUuid?: string;
  uuid?: string;
}
