/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {OrderItemRequestDto} from '../models/order-item-request-dto';

export interface OrderRequestDto {
  customerNotes?: string;
  orderItems?: Array<OrderItemRequestDto>;
}
