/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OrderItemResponse {
  productItemUuid?: string;
  quantity?: number;
  unitPrice?: number;
}
