/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {ProductItemIngredientRequestDto} from '../models/product-item-ingredient-request-dto';

export interface ProductItemRequestDto {
  category?: string;
  description?: string;
  ingredients?: Array<ProductItemIngredientRequestDto>;
  name?: string;
  price?: number;
}
