/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {ProductItemIngredientResponseDto} from '../models/product-item-ingredient-response-dto';

export interface ProductItemResponseDto {
  category?: 'BREAKFAST' | 'LUNCH' | 'DINNER' | 'DRINK' | 'SIDE_DISH' | 'FRIED_FOOD' | 'FAST_FOOD' | 'DESSERT';
  description?: string;
  ingredients?: Array<ProductItemIngredientResponseDto>;
  isEnabled?: boolean;
  name?: string;
  price?: number;
  uuid?: string;
}
