/* tslint:disable */
/* eslint-disable */

/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserRequestDto {
  email?: string;
  lastname?: string;
  name?: string;
  password?: string;
  phone?: string;
  roles?: Array<string>;
  username?: string;
}
