/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext} from '@angular/common/http';
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

import {BaseService} from '../base-service';
import {ApiConfiguration} from '../api-configuration';
import {StrictHttpResponse} from '../strict-http-response';

import {ApiGenericResponseString} from '../models/api-generic-response-string';
import {login, Login$Params} from '../fn/auth-rest-controller/login';

@Injectable({providedIn: 'root'})
export class AuthRestControllerService extends BaseService {
  /** Path part for operation `login()` */
  static readonly LoginPath = '/api/v1/auth/login';

  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseString>> {
    return login(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Observable<ApiGenericResponseString> {
    return this.login$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseString>): ApiGenericResponseString => r.body)
    );
  }

}
