/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext} from '@angular/common/http';
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

import {BaseService} from '../base-service';
import {ApiConfiguration} from '../api-configuration';
import {StrictHttpResponse} from '../strict-http-response';

import {addIngredient, AddIngredient$Params} from '../fn/ingredient-rest-controller/add-ingredient';
import {ApiGenericResponseIngredientResponseDto} from '../models/api-generic-response-ingredient-response-dto';
import {ApiGenericResponseListIngredientResponseDto} from '../models/api-generic-response-list-ingredient-response-dto';
import {ApiGenericResponseUuid} from '../models/api-generic-response-uuid';
import {getAllIngredients, GetAllIngredients$Params} from '../fn/ingredient-rest-controller/get-all-ingredients';
import {getIngredientById, GetIngredientById$Params} from '../fn/ingredient-rest-controller/get-ingredient-by-id';
import {updateIngredient, UpdateIngredient$Params} from '../fn/ingredient-rest-controller/update-ingredient';

@Injectable({providedIn: 'root'})
export class IngredientRestControllerService extends BaseService {
  /** Path part for operation `getIngredientById()` */
  static readonly GetIngredientByIdPath = '/api/v1/ingredients/{ingredientUuid}';
  /** Path part for operation `updateIngredient()` */
  static readonly UpdateIngredientPath = '/api/v1/ingredients/{ingredientUuid}';
  /** Path part for operation `getAllIngredients()` */
  static readonly GetAllIngredientsPath = '/api/v1/ingredients';
  /** Path part for operation `addIngredient()` */
  static readonly AddIngredientPath = '/api/v1/ingredients';

  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getIngredientById()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIngredientById$Response(params: GetIngredientById$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseIngredientResponseDto>> {
    return getIngredientById(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getIngredientById$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getIngredientById(params: GetIngredientById$Params, context?: HttpContext): Observable<ApiGenericResponseIngredientResponseDto> {
    return this.getIngredientById$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseIngredientResponseDto>): ApiGenericResponseIngredientResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateIngredient()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIngredient$Response(params: UpdateIngredient$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseIngredientResponseDto>> {
    return updateIngredient(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateIngredient$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateIngredient(params: UpdateIngredient$Params, context?: HttpContext): Observable<ApiGenericResponseIngredientResponseDto> {
    return this.updateIngredient$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseIngredientResponseDto>): ApiGenericResponseIngredientResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllIngredients()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllIngredients$Response(params?: GetAllIngredients$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseListIngredientResponseDto>> {
    return getAllIngredients(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllIngredients$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllIngredients(params?: GetAllIngredients$Params, context?: HttpContext): Observable<ApiGenericResponseListIngredientResponseDto> {
    return this.getAllIngredients$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseListIngredientResponseDto>): ApiGenericResponseListIngredientResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addIngredient()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addIngredient$Response(params: AddIngredient$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseUuid>> {
    return addIngredient(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addIngredient$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addIngredient(params: AddIngredient$Params, context?: HttpContext): Observable<ApiGenericResponseUuid> {
    return this.addIngredient$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseUuid>): ApiGenericResponseUuid => r.body)
    );
  }

}
