/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext} from '@angular/common/http';
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

import {BaseService} from '../base-service';
import {ApiConfiguration} from '../api-configuration';
import {StrictHttpResponse} from '../strict-http-response';

import {ApiGenericResponseListOrderResponseDto} from '../models/api-generic-response-list-order-response-dto';
import {ApiGenericResponseOrderResponseDto} from '../models/api-generic-response-order-response-dto';
import {ApiGenericResponseUuid} from '../models/api-generic-response-uuid';
import {createOrder, CreateOrder$Params} from '../fn/order-rest-controller/create-order';
import {getAllOrders, GetAllOrders$Params} from '../fn/order-rest-controller/get-all-orders';
import {getOrderByUuid, GetOrderByUuid$Params} from '../fn/order-rest-controller/get-order-by-uuid';
import {updateOrder, UpdateOrder$Params} from '../fn/order-rest-controller/update-order';

@Injectable({providedIn: 'root'})
export class OrderRestControllerService extends BaseService {
  /** Path part for operation `getOrderByUuid()` */
  static readonly GetOrderByUuidPath = '/api/v1/orders/{orderUuid}';
  /** Path part for operation `updateOrder()` */
  static readonly UpdateOrderPath = '/api/v1/orders/{orderUuid}';
  /** Path part for operation `getAllOrders()` */
  static readonly GetAllOrdersPath = '/api/v1/orders';
  /** Path part for operation `createOrder()` */
  static readonly CreateOrderPath = '/api/v1/orders';

  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOrderByUuid()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderByUuid$Response(params: GetOrderByUuid$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseOrderResponseDto>> {
    return getOrderByUuid(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOrderByUuid$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOrderByUuid(params: GetOrderByUuid$Params, context?: HttpContext): Observable<ApiGenericResponseOrderResponseDto> {
    return this.getOrderByUuid$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseOrderResponseDto>): ApiGenericResponseOrderResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOrder$Response(params: UpdateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseOrderResponseDto>> {
    return updateOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateOrder(params: UpdateOrder$Params, context?: HttpContext): Observable<ApiGenericResponseOrderResponseDto> {
    return this.updateOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseOrderResponseDto>): ApiGenericResponseOrderResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOrders()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders$Response(params?: GetAllOrders$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseListOrderResponseDto>> {
    return getAllOrders(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOrders$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOrders(params?: GetAllOrders$Params, context?: HttpContext): Observable<ApiGenericResponseListOrderResponseDto> {
    return this.getAllOrders$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseListOrderResponseDto>): ApiGenericResponseListOrderResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createOrder()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder$Response(params: CreateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseUuid>> {
    return createOrder(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createOrder$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createOrder(params: CreateOrder$Params, context?: HttpContext): Observable<ApiGenericResponseUuid> {
    return this.createOrder$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseUuid>): ApiGenericResponseUuid => r.body)
    );
  }

}
