/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext} from '@angular/common/http';
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

import {BaseService} from '../base-service';
import {ApiConfiguration} from '../api-configuration';
import {StrictHttpResponse} from '../strict-http-response';

import {addProductItem, AddProductItem$Params} from '../fn/product-item-rest-controller/add-product-item';
import {
  ApiGenericResponseListProductItemResponseDto
} from '../models/api-generic-response-list-product-item-response-dto';
import {ApiGenericResponseProductItemResponseDto} from '../models/api-generic-response-product-item-response-dto';
import {ApiGenericResponseUuid} from '../models/api-generic-response-uuid';
import {getAllProductItems, GetAllProductItems$Params} from '../fn/product-item-rest-controller/get-all-product-items';
import {
  getProductItemByUuid,
  GetProductItemByUuid$Params
} from '../fn/product-item-rest-controller/get-product-item-by-uuid';
import {updateProductItem, UpdateProductItem$Params} from '../fn/product-item-rest-controller/update-product-item';

@Injectable({providedIn: 'root'})
export class ProductItemRestControllerService extends BaseService {
  /** Path part for operation `getProductItemByUuid()` */
  static readonly GetProductItemByUuidPath = '/api/v1/product-items/{productItemUuid}';
  /** Path part for operation `updateProductItem()` */
  static readonly UpdateProductItemPath = '/api/v1/product-items/{productItemUuid}';
  /** Path part for operation `getAllProductItems()` */
  static readonly GetAllProductItemsPath = '/api/v1/product-items';
  /** Path part for operation `addProductItem()` */
  static readonly AddProductItemPath = '/api/v1/product-items';

  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProductItemByUuid()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductItemByUuid$Response(params: GetProductItemByUuid$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseProductItemResponseDto>> {
    return getProductItemByUuid(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProductItemByUuid$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProductItemByUuid(params: GetProductItemByUuid$Params, context?: HttpContext): Observable<ApiGenericResponseProductItemResponseDto> {
    return this.getProductItemByUuid$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseProductItemResponseDto>): ApiGenericResponseProductItemResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateProductItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProductItem$Response(params: UpdateProductItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseProductItemResponseDto>> {
    return updateProductItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateProductItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateProductItem(params: UpdateProductItem$Params, context?: HttpContext): Observable<ApiGenericResponseProductItemResponseDto> {
    return this.updateProductItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseProductItemResponseDto>): ApiGenericResponseProductItemResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllProductItems()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProductItems$Response(params?: GetAllProductItems$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseListProductItemResponseDto>> {
    return getAllProductItems(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllProductItems$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllProductItems(params?: GetAllProductItems$Params, context?: HttpContext): Observable<ApiGenericResponseListProductItemResponseDto> {
    return this.getAllProductItems$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseListProductItemResponseDto>): ApiGenericResponseListProductItemResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addProductItem()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addProductItem$Response(params: AddProductItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseUuid>> {
    return addProductItem(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addProductItem$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  addProductItem(params: AddProductItem$Params, context?: HttpContext): Observable<ApiGenericResponseUuid> {
    return this.addProductItem$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseUuid>): ApiGenericResponseUuid => r.body)
    );
  }

}
