/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext} from '@angular/common/http';
import {Injectable} from '@angular/core';
import {Observable} from 'rxjs';
import {map} from 'rxjs/operators';

import {BaseService} from '../base-service';
import {ApiConfiguration} from '../api-configuration';
import {StrictHttpResponse} from '../strict-http-response';

import {ApiGenericResponseUserResponseDto} from '../models/api-generic-response-user-response-dto';
import {createUser, CreateUser$Params} from '../fn/user-rest-controller/create-user';
import {getUserInfoByUuid, GetUserInfoByUuid$Params} from '../fn/user-rest-controller/get-user-info-by-uuid';

@Injectable({providedIn: 'root'})
export class UserRestControllerService extends BaseService {
  /** Path part for operation `createUser()` */
  static readonly CreateUserPath = '/api/v1/users';
  /** Path part for operation `getUserInfoByUuid()` */
  static readonly GetUserInfoByUuidPath = '/api/v1/users/{userUuid}';

  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser$Response(params: CreateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseUserResponseDto>> {
    return createUser(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser(params: CreateUser$Params, context?: HttpContext): Observable<ApiGenericResponseUserResponseDto> {
    return this.createUser$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseUserResponseDto>): ApiGenericResponseUserResponseDto => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getUserInfoByUuid()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserInfoByUuid$Response(params: GetUserInfoByUuid$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseUserResponseDto>> {
    return getUserInfoByUuid(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getUserInfoByUuid$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getUserInfoByUuid(params: GetUserInfoByUuid$Params, context?: HttpContext): Observable<ApiGenericResponseUserResponseDto> {
    return this.getUserInfoByUuid$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApiGenericResponseUserResponseDto>): ApiGenericResponseUserResponseDto => r.body)
    );
  }

}
