/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {ApiGenericResponseOrderResponseDto} from '../../models/api-generic-response-order-response-dto';
import {OrderRequestDto} from '../../models/order-request-dto';

export interface UpdateOrder$Params {
  orderUuid: string;
  body: OrderRequestDto
}

export function updateOrder(http: HttpClient, rootUrl: string, params: UpdateOrder$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseOrderResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateOrder.PATH, 'put');
  if (params) {
    rb.path('orderUuid', params.orderUuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseOrderResponseDto>;
    })
  );
}

updateOrder.PATH = '/api/v1/orders/{orderUuid}';
