/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {ApiGenericResponseUuid} from '../../models/api-generic-response-uuid';
import {IngredientRequestDto} from '../../models/ingredient-request-dto';

export interface AddIngredient$Params {
  body: IngredientRequestDto
}

export function addIngredient(http: HttpClient, rootUrl: string, params: AddIngredient$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseUuid>> {
  const rb = new RequestBuilder(rootUrl, addIngredient.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseUuid>;
    })
  );
}

addIngredient.PATH = '/api/v1/ingredients-page';
