/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {ApiGenericResponseIngredientResponseDto} from '../../models/api-generic-response-ingredient-response-dto';

export interface GetIngredientById$Params {
  ingredientUuid: string;
}

export function getIngredientById(http: HttpClient, rootUrl: string, params: GetIngredientById$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseIngredientResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getIngredientById.PATH, 'get');
  if (params) {
    rb.path('ingredientUuid', params.ingredientUuid, {});
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseIngredientResponseDto>;
    })
  );
}

getIngredientById.PATH = '/api/v1/ingredients/{ingredientUuid}';
