/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {
  ApiGenericResponseListIngredientResponseDto
} from '../../models/api-generic-response-list-ingredient-response-dto';

export interface GetAllIngredients$Params {
}

export function getAllIngredients(http: HttpClient, rootUrl: string, params?: GetAllIngredients$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseListIngredientResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getAllIngredients.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseListIngredientResponseDto>;
    })
  );
}

getAllIngredients.PATH = '/api/v1/ingredients';
