/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {ApiGenericResponseIngredientResponseDto} from '../../models/api-generic-response-ingredient-response-dto';
import {IngredientRequestDto} from '../../models/ingredient-request-dto';

export interface UpdateIngredient$Params {
  ingredientUuid: string;
  body: IngredientRequestDto
}

export function updateIngredient(http: HttpClient, rootUrl: string, params: UpdateIngredient$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseIngredientResponseDto>> {
  const rb = new RequestBuilder(rootUrl, updateIngredient.PATH, 'put');
  if (params) {
    rb.path('ingredientUuid', params.ingredientUuid, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseIngredientResponseDto>;
    })
  );
}

updateIngredient.PATH = '/api/v1/ingredients/{ingredientUuid}';
