/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {
  ApiGenericResponseListProductItemResponseDto
} from '../../models/api-generic-response-list-product-item-response-dto';

export interface GetAllProductItems$Params {
}

export function getAllProductItems(http: HttpClient, rootUrl: string, params?: GetAllProductItems$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseListProductItemResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getAllProductItems.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseListProductItemResponseDto>;
    })
  );
}

getAllProductItems.PATH = '/api/v1/product-items';
