/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import {HttpClient, HttpContext, HttpResponse} from '@angular/common/http';
import {Observable} from 'rxjs';
import {filter, map} from 'rxjs/operators';
import {StrictHttpResponse} from '../../strict-http-response';
import {RequestBuilder} from '../../request-builder';

import {ApiGenericResponseProductItemResponseDto} from '../../models/api-generic-response-product-item-response-dto';

export interface GetProductItemByUuid$Params {
  productItemUuid: string;
}

export function getProductItemByUuid(http: HttpClient, rootUrl: string, params: GetProductItemByUuid$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiGenericResponseProductItemResponseDto>> {
  const rb = new RequestBuilder(rootUrl, getProductItemByUuid.PATH, 'get');
  if (params) {
    rb.path('productItemUuid', params.productItemUuid, {});
  }

  return http.request(
    rb.build({responseType: 'blob', accept: '*/*', context})
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiGenericResponseProductItemResponseDto>;
    })
  );
}

getProductItemByUuid.PATH = '/api/v1/product-items/{productItemUuid}';
